---
title           : "Transdiagnostic Written Exposure Therapy: a Randomized Control Trial comparing WET to past and future events"
shorttitle      : "Past-Future WET"
date            : "`r Sys.setlocale('LC_TIME', 'C'); format(Sys.time(), '%d\\\\. %B %Y')`"

author: 
  - name        : Snir Barzilai
    affiliation : 1
  - name        : Elad Zlotnick
    affiliation : 1
  - name        : Hila Sorka
    affiliation : 1
  - name        : Jonathan D. Huppert
    affiliation : 1

affiliation:
  - id          : 1
    institution : The Hebrew Univeristy of Jerusalem

output: prereg::prereg_pdf

# need to downgrade pandoc to v3.1.6 for refrences to work
bibliography: "`r normalizePath('~/projects/zettlr/zotero.json')`"
csl: "`r normalizePath('~/projects/zettlr/apa.csl')`"
---
```{r, include=FALSE}
options(tinytex.verbose = TRUE)
```

# Study Information

## Title
<!-- Provide the working title of your study. It may be the same title that you submit for publication of your final manuscript, but it is not a requirement. The title should be a specific and informative description of a project. Vague titles such as 'Fruit fly preregistration plan' are not appropriate.

Example: Effect of sugar on brownie tastiness. -->

`r rmarkdown::metadata$title`


## Description
<!-- Please give a brief description of your study, including some background, the purpose of the of the study, or broad research questions. The description should be no longer than the length of an abstract. It can give some context for the proposed study, but great detail is not needed here for your preregistration.

Example: Though there is strong evidence to suggest that sugar affects taste preferences, the effect has never been demonstrated in brownies. Therefore, we will measure taste preference for four different levels of sugar concentration in a standard brownie recipe to determine if the effect exists in this pastry. -->

The goal of the current project is to evaluate a self-administered, brief online written exposure therapy (WET) intervention.
This intervention was adapted from WET for PTSD [@sloanWrittenExposureTherapy2019] and is designed to be transdiagnostic, focus on participants' core fears [@huppertCoreFearsValues2012] and use an immersive perspective similar to imaginal exposure [IE\; @asnaaniUpdatingWatsonMarks2016].
Furthermore, it aims to compare the processes underlying exposure to past vs. future events.
The interventions will be tested within an online randomized controlled trial with a trans-diagnostic sample of individuals with high levels of anxiety.
We will test treatment efficacy as measured by change in anxiety and functioning.
Furthermore we will investigate patterns of change and potential mechanisms of change as a function of treatment group.

## Hypotheses
<!-- List specific, concise, and testable hypotheses. Please state if the hypotheses are directional or non-directional. If directional, state the direction. A predicted effect is also appropriate here. If a specific interaction or moderation is important to your research, you can list that as a separate hypothesis.

Example: If taste affects preference, then mean preference indices will be higher with higher concentrations of sugar. -->

1. WET is more effective than control in reducing pathological anxiety, in both past and future conditions.
2. Changes in likelihood thought action fusion, and in distress tolerance, will change together with changes in pathological anxiety. This could indicate the possibility that these mechanism serves as mediators, and provide motivation for further studies.
3. Changes in details valence will be larger in congruent conditions
4. Changes in valence of memory details will be related to changes in valence of details in future imagery, and vice versa. 

# Design Plan
<!-- In this section, you will be asked to describe the overall design of your study. Remember that this research plan is designed to register a single study, so if you have multiple experimental designs, please complete a separate preregistration. -->

The study is a Randomized Controlled Trial (RCT).

## Study type

**Experiment**. A researcher randomly assigns treatments to study subjects, this includes field or lab experiments. This is also known as an intervention experiment and includes randomized controlled trials.

## Blinding
<!-- Blinding describes who is aware of the experimental manipulations within a study. Select all that apply. Is there any additional blinding in this study? -->

For studies that involve human subjects, they will not know the treatment group to which they have been assigned.
Personnel who interact directly with the study subjects (either human or non-human subjects) will not be aware of the assigned treatments.

## Study design
<!-- Describe your study design. Examples include two-group, factorial, randomized block, and repeated measures. Is it a between (unpaired), within-subject (paired), or mixed design? Describe any counterbalancing required. Typical study designs for observation studies include cohort, cross sectional, and case-control studies.

This question has a variety of possible answers. The key is for a researcher to be as detailed as is necessary given the specifics of their design. Be careful to determine if every parameter has been specified in the description of the study design. There may be some overlap between this question and the following questions. That is OK, as long as sufficient detail is given in one of the areas to provide all of the requested information. For example, if the study design describes a complete factorial, 2 X 3 design and the treatments and levels are specified previously, you do not have to repeat that information.

Example: We have a between subjects design with 1 factor (sugar by mass) with 4 levels. -->
* Participants will be randomly assigned to one of three groups: 
  * Past WET (past)
  * Future WET (future)
  * Expressive writing (control)
* Furthermore, one third of participants will be randomly assigned to a two week waiting list where symptoms and mechanisms will be measured twice.
* All groups will engage in four sessions of writing and follow-up sessions after one week and three months.
* Symptom measures and mechanisms will be assessed before the first and after the last writing sessions.
* Symptoms will be measured at each writing session. And again at the follow-up sessions.
* Though action fusion will be measured at the follow-up sessions.

Treatment efficacy will be investigated within a pretest-posttest control group design (see below).
The primary outcome will be change in OASIS, though change in WSAS and all measured mechanisms will be considered secondary outcomes.
Furthermore, we will investigate the covariation between changes in OASIS and change in each mechanism.

## Randomization
<!-- If you are doing a randomized study, how will you randomize, and at what level? Typical randomization techniques include: simple, block, stratified, and adaptive covariate randomization. If randomization is required for the study, the method should be specified here, not simply the source of random numbers.

Example: We will use block randomization, where each participant will be randomly assigned to one of the four equally sized, predetermined blocks. The random number list used to create these four blocks will be created using the web applications available at https://random.org. -->

Participants will be randomly assigned to the treatment and control groups in a 110:110:50 ratio, with the treatment groups being larger than the control group.
Furthermore, participants with low anxiety (4 <= OASIS < 8) will be randomized separately from participants with high anxiety (OASIS>=8), to ensure equal distribution of severity between the groups.
This will be accomplished through block randomization, where participants are randomly assigned within predetermined blocks.
The randomization process is integrated into the experiment program code (Qualtrics).

# Sampling Plan
<!-- In this section we’ll ask you to describe how you plan to collect samples, as well as the number of samples you plan to collect and your rationale for this decision. Please keep in mind that the data described in this section should be the actual data used for analysis, so if you are using a subset of a larger dataset, please describe the subset that will actually be used in your study. -->


## Existing data
<!-- Preregistration is designed to make clear the distinction between confirmatory tests, specified prior to seeing the data, and exploratory analyses conducted after observing the data. Therefore, creating a research plan in which existing data will be used presents unique challenges. Please select the description that best describes your situation. Please do not hesitate to contact us if you have questions about how to answer this question (prereg@cos.io). -->

**Registration prior to creation of data**. As of the date of submission of this research plan for preregistration, the data have not yet been collected, created, or realized. 

## Explanation of existing data
<!-- If you indicate that you will be using some data that already exist in this study, please describe the steps you have taken to assure that you are unaware of any patterns or summary statistics in the data. This may include an explanation of how access to the data has been limited, who has observed the data, or how you have avoided observing any analysis of the specific data you will use in your study.

An appropriate instance of using existing data would be collecting a sample size much larger than is required for the study, using a small portion of it to conduct exploratory analysis, and then registering one particular analysis that showed promising results. After registration, conduct the specified analysis on that part of the dataset that had not been investigated by the researcher up to that point.

Example: An appropriate instance of using existing data would be collecting a sample size much larger than is required for the study, using a small portion of it to conduct exploratory analysis, and then registering one particular analysis that showed promising results. After registration, conduct the specified analysis on that part of the dataset that had not been investigated by the researcher up to that point. -->

No use of existing data


## Data collection procedures
<!-- Please describe the process by which you will collect your data. If you are using human subjects, this should include the population from which you obtain subjects, recruitment efforts, payment for participation, how subjects will be selected for eligibility from the initial pool (e.g. inclusion and exclusion rules), and your study timeline. For studies that donÍt include human subjects, include information about how you will collect samples, duration of data gathering efforts, source or location of samples, or batch numbers you will use.

The answer to this question requires a specific set of instructions so that another person could repeat the data collection procedures and recreate the study population. Alternatively, if the study population would be unable to be reproduced because it relies on a specific set of circumstances unlikely to be recreated (e.g., a community of people from a specific time and location), the criteria and methods for creating the group and the rationale for this unique set of subjects should be clear.

Example: Participants will be recruited through advertisements at local pastry shops. Participants will be paid $10 for agreeing to participate (raised to $30 if our sample size is not reached within 15 days of beginning recruitment). Participants must be at least 18 years old and be able to eat the ingredients of the pastries. -->


Participants will be sampled on the Prolific platform of online research.
Participants will be paid 9 $\pounds$/hour for participation.
Inclusion criteria will include high pathological anxiety [ greater than 4 on the Overall Anxiety Severity and Impairment Scale\; OASIS, @normanDevelopmentValidationOverall2006],
and impaired daily function [at least one item scored above 2 on the Work and Social Adjustment Scale. WSAS\; @mundtWorkSocialAdjustment2002].
Exclusion criteria are severe depression [greater than 14 on the PHQ\; @kroenkePHQ8MeasureCurrent2009], post-trauma [greater than 6 on the short PCL-5\; @blevinsPosttraumaticStressDisorder2015], or psychotic symptoms [items 19 or 20 from the DIAMOND screener\; @tolinPsychometricPropertiesStructured2018].
In addition, English as a fluent language is required.
Furthermore, participants who have reported autism, head injury, or reading and writing difficulties in the Prolific system  will be excluded.
Finally, only experienced users on the Prolific platform with an approval rate of above 95, and with minimum previous submissions of 300 will be allowed to participate in this study.
We will request that prolific sample an ethnically diverse sample.

## Sample size
<!-- Describe the sample size of your study. How many units will be analyzed in the study? This could be the number of people, birds, classrooms, plots, interactions, or countries included. If the units are not individuals, then describe the size requirements for each unit. If you are using a clustered or multilevel design, how many units are you collecting at each level of the analysis? For some studies, this will simply be the number of samples or the number of clusters. For others, this could be an expected range, minimum, or maximum number.

Example: Our target sample size is 280 participants. We will attempt to recruit up to 320, assuming that not all will complete the total task. -->
Our target sample size is 243 participants. We will attempt to recruit up to 270, assuming that not all will complete the full task.

<!-- ## Sample size rationale
<!-- This could include a power analysis or an arbitrary constraint such as time, money, or personnel. This gives you an opportunity to specifically state how the sample size will be determined. A wide range of possible answers is acceptable; remember that transparency is more important than principled justifications. If you state any reason for a sample size upfront, it is better than stating no reason and leaving the reader to "fill in the blanks." Acceptable rationales include: a power analysis, an arbitrary number of subjects, or a number based on time or monetary constraints.

Example: We used the software program G*Power to conduct a power analysis. Our goal was to obtain .95 power to detect a medium effect size of .25 at the standard .05 alpha error probability. -->

<!--
A power analysis was conducted with the assumption of an intraclass correlation coefficient (ICC) of 0.5 and an effect size of 0.4, revealing that a sample size of 130 participants per treatment group would provide 0.8 power.
-->

## Stopping rule
<!-- If your data collection procedures do not give you full control over your exact sample size, specify how you will decide when to terminate your data collection. 

You may specify a stopping rule based on p-values only in the specific case of sequential analyses with pre-specified checkpoints, alphas levels, and stopping rules. Unacceptable rationales include stopping based on p-values if checkpoints and stopping rules are not specified. If you have control over your sample size, then including a stopping rule is not necessary, though it must be clear in this question or a previous question how an exact sample size is attained.

Example: We will post participant sign-up slots by week on the preceding Friday night, with 20 spots posted per week. We will post 20 new slots each week if, on that Friday night, we are below 320 participants. -->

We will recruit until we reach our sample size, or until after 6 months from the beginning of the recruitment. 

# Variables

<!-- In this section you can describe all variables (both manipulated and measured variables) that will later be used in your confirmatory analysis plan. In your analysis plan, you will have the opportunity to describe how each variable will be used. If you have variables which you are measuring for exploratory analyses, you are not required to list them, though you are permitted to do so. -->

## Manipulated variables
<!-- Describe all variables you plan to manipulate and the levels or treatment arms of each variable. This is not applicable to any observational study. For any experimental manipulation, you should give a precise definition of each manipulated variable. This must include a precise description of the levels at which each variable will be set, or a specific definition for each categorical treatment. For example, “loud or quiet,” should instead give either a precise decibel level or a means of recreating each level. 'Presence/absence' or 'positive/negative' is an acceptable description if the variable is precisely described.

Example: We manipulated the percentage of sugar by mass added to brownies. The four levels of this categorical variable are: 15%, 20%, 25%, or 40% cane sugar by mass. -->

We manipulate the task participants engage in by providing different instructions.

* The past group receive instructions to write about a significant memory.
* The future group receive instructions to write about their core threats.
* The control group receive instructions to write about a daily activity.

## Measured variables
<!-- Describe each variable that you will measure. This will include outcome measures, as well as any predictors or covariates that you will measure. You do not need to include any variables that you plan on collecting if they are not going to be included in the confirmatory analyses of this study.

Observational studies and meta-analyses will include only measured variables. As with the previous questions, the answers here must be precise. For example, 'intelligence,' 'accuracy,' 'aggression,' and 'color' are too vague. Acceptable alternatives could be 'IQ as measured by Wechsler Adult Intelligence Scale' 'percent correct,' 'number of threat displays,' and 'percent reflectance at 400 nm.'

Example: The single outcome variable will be the perceived tastiness of the single brownie each participant will eat. We will measure this by asking participants ‘How much did you enjoy eating the brownie’ (on a scale of 1-7, 1 being 'not at all', 7 being 'a great deal') and 'How good did the brownie taste' (on a scale of 1-7, 1 being 'very bad', 7 being 'very good'). -->

**Symptoms**

1. Pathological anxiety will be measured via the Overall Anxiety Severity and Impairment Scale [OASIS\; @normanDevelopmentValidationOverall2006].
2. Daily functioning will be measured via Work and Social Adjustment Scale [WSAS\; @mundtWorkSocialAdjustment2002].

**Mechanisms**

1. Thought Action Fusion questionnaire; broken into moral and likelihood subscales [TAF\; @amirThoughtactionFusionIndividuals2001]
2. Distress Tolerance Scale [DTS\; @simonsDistressToleranceScale2005]
3. Brief Core Schema Scale [BCSS\; @fowlerBriefCoreSchema2006]
4. Transdiagnostic Intrusive Imagery Inventory (TIII)
5. Anxiety Control Questionnaire- Revised [ACQ\; @brownStructurePerceivedEmotional2004]
6. State Mindfulness questionnaire [SMS\; @tanayStateMindfulnessScale2013]
7. Five Facet Mindfulness Questionnaire [FFMQ\; @baerFiveFacetMindfulness2022]
8. White Bear Suppression Inventory [WBSI\; @wegnerChronicThoughtSuppression1994]
9. Self appraisal illness questionnaire [SAIQ\; @marksSelfAppraisalIllnessQuestionnaire2000]
10. Self report insight
11. Self Compassion Scale [SCS\; @babenkoMeasuringSelfCompassionMedical2019]

**Memory Details**

We will code the *memory* and *future imagery* narratives provided by the participants at the first session and at the post session according to the Autobiographical Interview standardized coding system [@levineAgingAutobiographicalMemory2002].
This produces a valence score for each narrative.

## Indices
<!-- If any measurements are  going to be combined into an index (or even a mean), what measures will you use and how will they be combined? Include either a formula or a precise description of your method. If your are using a more complicated statistical method to combine measures (e.g. a factor analysis), you can note that here but describe the exact method in the analysis plan section.

If you are using multiple pieces of data to construct a single variable, how will this occur? Both the data that are included and the formula or weights for each measure must be specified. Standard summary statistics, such as "means" do not require a formula, though more complicated indices require either the exact formula or, if it is an established index in the field, the index must be unambiguously defined. For example, "biodiversity index" is too broad, whereas "Shannon’s biodiversity index" is appropriate.

Example: We will take the mean of the two questions above to create a single measure of 'brownie enjoyment.'  -->

We do not plan to create indices

# Analysis Plan
<!-- You may describe one or more confirmatory analysis in this preregistration. Please remember that all analyses specified below must be reported in the final article, and any additional analyses must be noted as exploratory or hypothesis generating.

A confirmatory analysis plan must state up front which variables are predictors (independent) and which are the outcomes (dependent), otherwise it is an exploratory analysis. You are allowed to describe any exploratory work here, but a clear confirmatory analysis is required. -->


## Statistical models
<!-- What statistical model will you use to test each hypothesis? Please include the type of model (e.g. ANOVA, multiple regression, SEM, etc) and the specification of the model (this includes each variable that will be included as predictors, outcomes, or covariates). Please specify any interactions, subgroup analyses, pairwise or complex contrasts, or follow-up tests from omnibus tests. If you plan on using any positive controls, negative controls, or manipulation checks you may mention that here. Remember that any test not included here must be noted as an exploratory test in your final article.

This is perhaps the most important and most complicated question within the preregistration. As with all of the other questions, the key is to provide a specific recipe for analyzing the collected data. Ask yourself: is enough detail provided to run the same analysis again with the information provided by the user? Be aware for instances where the statistical models appear specific, but actually leave openings for the precise test. See the following examples:

- If someone specifies a 2x3 ANOVA with both factors within subjects, there is still flexibility with the various types of ANOVAs that could be run. Either a repeated measures ANOVA (RMANOVA) or a multivariate ANOVA (MANOVA) could be used for that design, which are two different tests. 
- If you are going to perform a sequential analysis and check after 50, 100, and 150 samples, you must also specify the p-values you’ll test against at those three points.

Example:  We will use a one-way between subjects ANOVA to analyze our results. The manipulated, categorical independent variable is 'sugar' whereas the dependent variable is our taste index. -->

We use a pre-test post-test control group design.
We will analyze the data using a multilevel ANCOVA design [@bodnerDetectingDifferentiatingDirection2018; @vanbreukelenANCOVACHANGEBaseline2013].
Responses will be modeled as ordered logit, using a cumulative link function [@mccullaghRegressionModelsOrdinal1980].
Furthermore, they will be treated within a graded response model IRT approach [@samejimaGradedResponseModels2016].
A similar approach can be found in Wang and Nydick [@wangLongitudinalItemResponse2020].
Change is modeled as an additive process where changes within the treatment are considered linear.

The model is defined as follows:

```{=latex}
\begin{align*}
R_{itq} &\sim \text{Ordered-logit}(\phi_{itq}, \kappa) \tag{likelihood} \\
\phi_{itq} &= \alpha_q \cdot (\theta_{it} - \beta_q) \tag{IRT model}  \\
\theta_{it} &= -b_{0i} \cdot t \cdot 1_{\{t<0\}} \\
            &\quad + b_{1i} \\
            &\quad + b_{2i} \cdot \min(t-1,\ 3) \cdot 1_{\{t > 0\}} \\
            &\quad + b_{3i} \cdot 1_{\{t=5\}} \\
            &\quad + b_{4i} \cdot 1_{\{t=6\}} \tag{change model} \\
b_{0i} &= \bar{b} + u_{0i} \tag{$\Delta$ of waitlist} \\
b_{1i} &= \bar{b}_{1,\text{condition}} + u_{1i} \tag{$\theta$ at baseline} \\
b_{2i} &= \bar{b}_{2,\text{condition}} + u_{2i} \tag{$\Delta$ at intervention} \\
b_{3i} &= \bar{b}_{3,\text{condition}} + u_{3i} \tag{$\Delta$ at FU\_1} \\
b_{4i} &= \bar{b}_{4,\text{condition}} + u_{4i} \tag{$\Delta$ at FU\_2} \\
\kappa &\sim \text{Normal}(0,1.5) \tag{cutpoints} \\
\beta_q &\sim \text{Normal}(0,1) \tag{IRT location} \\
\alpha_q &\sim \text{Log-Normal}(0,0.5) \tag{IRT discrimination} \\
\bar{b}_{1,\text{condition}} &\sim \text{Normal}(0,1.5) \tag{$\theta$ intercept} \\
\bar{b}_{[0,2,3,4],\text{condition}} &\sim \text{Normal}(0,0.5) \tag{$\theta$ slopes} \\
\sigma_{0\ldots4} &\sim \text{Exponential}(1) \tag{scale for $u$} \\
\rho &\sim \text{LKJcorr}(5) \tag{correlation matrix} \\
\Sigma &= \text{diag}(\sigma_{0\ldots4}) \cdot \rho \cdot \text{diag}(\sigma_{0\ldots4}) \tag{covariance matrix} \\
\begin{bmatrix} u_{0i} \\ u_{1i} \\ u_{2i} \\ u_{3i} \\ u_{4i} \end{bmatrix} &\sim
\text{MVNormal} \left( \begin{bmatrix} 0\\0\\0\\0\\0 \end{bmatrix}, \Sigma \right) \tag{person effects}
\end{align*}
```

Where $R_{itq}$ is the response to question $q$ at time $t$ by participant $i$.
And *condition* is the condition of the participant.
Time is coded so that the baseline is 0 and waitlist are negative.

We will evaluate models via WAIC [@watanabeAsymptoticEquivalenceBayes2010], where the criterion for inclusion is an improvement of at least 10 points in the WAIC.

All estimates will be performed in a Bayesian framework, and when appropriate will use non-centered parameterization. 

**Hypothesis 1**: WET is more effective than control.

The primary outcome is the effect size of WET.
The estimands of interest are the treatment effects at followup vs. the effect at waitlist.

* $\Delta_0 = 2 \cdot \bar{b_0}$
* $\Delta_{1,condition} = 3 \cdot \bar{b}_{2,\text{condition}} + \bar{b}_{3,\text{condition}}$
* $\Delta_{2,condition}= 3 \cdot \bar{b}_{2,\text{condition}} + \bar{b}_{4,\text{condition}}$

We will report the combined effect of the active treatments vs. the control.
Our main outcome is OASIS, though we will explore the outcome of running the model for each of the symptoms and mechanisms measured.

* We expect the effect of both treatments to be better than wait list ($\Delta_{1,treatment} >  \Delta_0$).
* We expect no difference between the treatment groups ($\Delta_{1..2,past} \approx \Delta_{1..2,future}$.
* We expect treatments (combined) to be better than control $\Delta_{1..2,treatment} > \Delta_{1..2,control}$.

**Hypothesis 2**: Proposed mechanisms and symptoms change together.

We expect mechanisms of treatment to change at the same rate as the treatment.
The lack of such a correlation suggests that there is no causal relationship between mechanism and symptoms.
We will investigate this notion by estimating each of these mechanisms within the same model as the OASIS.
We will use the same measurement model and link.
However, individual change parameters ($u$) of both models will be sampled from the same multi-variate normal distribution [@baldwinAnalyzingMultipleOutcomes2014;@suvakMultilevelRegressionAnalyses2009].
This will allow to directly estimate the correlation between the two change scores.
In particular, we hypothesis the posterior correlation between the individual change parameters of the OASIS and mechanisms will be greater than one.
This hypothesis applies in particular to TAF-likelihood and DTS, the correlation for the other mechanisms will be explored.

**Hypothesis 3**: Changes in details valence will be larger in congruent conditions

* We expect the valence of memory details to change more in the WET past condition than the WET future condition.
* We expect the valence of future imagery details to change more in the WET future condition than the WET past condition.

**Hypothesis 4**: Changes in valence of memory details will be related to changes in valence of details in future imagery, and vice versa. 

For Hypothesis 3 and 4, we will replace the IRT model with the simple sum score.

## Transformations
<!-- If you plan on transforming, centering, recoding the data, or will require a coding scheme for categorical variables, please describe that process. If any categorical predictors are included in a regression, indicate how those variables will be coded (e.g. dummy coding, summation coding, etc.) and what the reference category will be.

Example: The "Effect of sugar on brownie tastiness" does not require any additional transformations. However, if it were using a regression analysis and each level of sweet had been categorically described (e.g. not sweet, somewhat sweet, sweet, and very sweet), 'sweet' could be dummy coded with 'not sweet' as the reference category. -->

We do not plan to transform the data.
Time will be zero base encoded (pre-treatment will be coded as negative).

## Inference criteria
<!-- What criteria will you use to make inferences? Please describe the information youÍll use (e.g. p-values, bayes factors, specific model fit indices), as well as cut-off criterion, where appropriate. Will you be using one or two tailed tests for each of your analyses? If you are comparing multiple conditions or testing multiple hypotheses, will you account for this?

p-values, confidence intervals, and effect sizes are standard means for making an inference, and any level is acceptable, though some criteria must be specified in this or previous fields. Bayesian analyses should specify a Bayes factor or a credible interval. If you are selecting models, then how will you determine the relative quality of each? In regards to multiple comparisons, this is a question with few "wrong" answers. In other words, transparency is more important than any specific method of controlling the false discovery rate or false error rate. One may state an intention to report all tests conducted or one may conduct a specific correction procedure; either strategy is acceptable.

Example: We will use the standard p<.05 criteria for determining if the ANOVA and the post hoc test suggest that the results are significantly different from those expected if the null hypothesis were correct. The post-hoc Tukey-Kramer test adjusts for multiple comparisons. -->

We will use a credible interval of 89% [@mcelreathStatisticalRethinkingBayesian2020].
Models will be selected via WAIC [@watanabeAsymptoticEquivalenceBayes2010] and PSIS [@vehtariParetoSmoothedImportance2021], where the criterion for prefering a model is a relative weight of $.9$.

## Data exclusion
<!-- How will you determine what data or samples, if any, to exclude from your analyses? How will outliers be handled? Will you use any awareness check? Any rule for excluding a particular set of data is acceptable. One may describe rules for excluding a participant or for identifying outlier data.

Example: No checks will be performed to determine eligibility for inclusion besides verification that each subject answered each of the three tastiness indices. Outliers will be included in the analysis. -->

We will treat measurements with a penalty greater than $1$ in the WAIC and Pareto $k$ greater than $.5$ in the PSIS  as outliers.
If these are relatively few, and we fail to model them, they will be excluded from analysis.

## Missing data
<!-- How will you deal with incomplete or missing data? Any relevant explanation is acceptable. As a final reminder, remember that the final analysis must follow the specified plan, and deviations must be either strongly justified or included as a separate, exploratory analysis.

Example: If a subject does not complete any of the three indices of tastiness, that subject will not be included in the analysis. -->

All subjects that start the intervention in the first session will be included in the analysis.
However, we will exclude any individual that clearly did not participate in the task, for example: individuals that wrote gibberish or text that clearly did not relate to the task.

Missing data will be imputed via Bayesian imputation.
We will assume that missiningness may be affected both by baseline trait levels and by difficulty completing the task
(notably, any missingness due to innefectivness of the task can not be estimated in this study).

## Exploratory analyses (optional)
<!-- If you plan to explore your data set to look for unexpected differences or relationships, you may describe those tests here. An exploratory test is any test where a prediction is not made up front, or there are multiple possible tests that you are going to use. A statistically significant finding in an exploratory test is a great way to form a new confirmatory hypothesis, which could be registered at a later time.

Example: We expect that certain demographic traits may be related to taste preferences. Therefore, we will look for relationships between demographic variables (age, gender, income, and marital status) and the primary outcome measures of taste preferences. -->

We intend to explore the effects of treatment when controlling for treatment adherance as encoded by external judges.

# References
## 
\vspace{-2pc}
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{-1in}
\setlength{\parskip}{8pt}
\noindent
