---
title: "Exploring change"
author: "Elad Zlotnick"
date: "`r format(Sys.time(), '%d-%m-%Y %H:%M')`"
output: html_document
toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,warning = FALSE, message = FALSE)
library(tidyverse)
library(rethinking)
library(here)
library(glue)
library(kableExtra)
source(here::here('scripts', 'load_data.R'))
source(here::here('scripts', 'model.helpers.R'))
```

# Change models
Following are models of measures vs. time.

```{r, echo=FALSE, results='asis'}
models_list = c( 'oasis', 'wsas', 'dts','taf_m','taf_l', 'bcss_self_neg', 'bcss_other_neg','bcss_self_pos', 'bcss_other_pos','tiii','ifs', 'scs', 'mcq_confidence','mcq_worry','mcq_self','mcq_danger','mcq_control')

src = lapply(models_list, function(mname) {
  knitr::knit_expand(here('scripts','change.template.Rmd'),mname=mname)
})
res = knitr::knit_child(text = unlist(src), quiet = TRUE)
cat(res, sep = '\n')
```





```{r, echo=FALSE}
table_data <- data.frame(
)

for (mname in models_list){
  knitr::asis_output(paste0('\n## Model: ', mname, '\n'))
  
  d = data_long %>% filter(measure == mname, !is.na(value), wave>0)
  m = model.change(d, mname)
  post = extract.samples(m)
  prec = precis(m, depth=9)
  
  new_row = d %>%
    filter(wave %in% c(1, 4)) %>%                    # Select waves 1 and 4
    group_by(condition, wave, id) %>%                # Group by condition and wave
    summarise(.groups = 'drop_last', value = sum(value)) %>%
    summarise(
      .groups = 'drop_last',
      mean_value = mean(value, na.rm = TRUE),        # Calculate mean
      sd_value = sd(value, na.rm = TRUE)             # Calculate standard deviation
    ) %>%
    ungroup %>%
    mutate(mean_sd = glue("{round(mean_value, 2)} ({round(sd_value, 2)})")) %>%
    unite("condition_wave", condition, wave, sep = "_wave", remove = FALSE) %>%
    select(condition_wave, mean_sd) %>%
    pivot_wider(names_from = condition_wave, values_from = mean_sd) %>%
    mutate(
      pTreatEffect = mean(post$bbar_treatment[,1]<0) %>% round(2),
      pCtrlEffect = mean(post$bbar_treatment[,2]<0) %>% round(2),
      pTreatBetter = mean((post$bbar_treatment[,1] - post$bbar_treatment[,2])<0) %>% round(2),
      maxRhat = max(prec$rhat, na.rm = TRUE),
      minESS = min(prec$ess_bulk, na.rm = TRUE)
    ) %>%
    add_column(name = mname, .before = 1)
    table_data = bind_rows(table_data, new_row)
}

kableExtra::kable(table_data)
```


# Mediation/moderation

```{r mech-back, include=FALSE, results='asis'}
models_list = c('wsas', 'dts','taf_m','taf_l', 'bcss_self_neg', 'bcss_other_neg','bcss_self_pos', 'bcss_other_pos','tiii','ifs', 'scs', 'mcq_confidence','mcq_worry','mcq_self','mcq_danger','mcq_control')

table_data <- data.frame(name = character()) 

d_x = data_long %>% filter(measure == 'oasis', !is.na(value), wave>0)
for (mname in models_list){
  d_m = data_long %>% filter(measure == mname, !is.na(value), wave>0)
  m = model.mechanism(d_x, d_m, mname)
  post = extract.samples(m)
  prec = precis(m, depth=9)
  
  bayesep = function(x){sprintf("%.2f (%.2f)", mean(x), mean(x > 0))}
  new_row = data.frame(
      name = mname,
      XMcorrelated = bayesep(post$Rho[,1,4]),
      modTre = bayesep(post$Rho[,4,2]),
      modFU = bayesep(post$Rho[,4,3]),
      medTre = bayesep(post$Rho[,5,2]),
      medFU = bayesep(post$Rho[,5,3]),
      maxRhat = max(prec$rhat, na.rm = TRUE),
      minESS = min(prec$ess_bulk, na.rm = TRUE)
    ) 
  table_data = bind_rows(table_data, new_row)
}
```

```{r mech, include=TRUE, results='asis'}
kableExtra::kable(table_data)
```