---
title             : "Transdiagnostic Written Exposure Therapy: Piloting an Online Intervention"
shorttitle        : "WET"

author: 
  - name          : "Elad Zlotnick"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : 
      Department of Psychology, The Hebrew University of Jerusalem, Mount Scopus,
      Jerusalem 91905, Israel
    email         : "elad.zlotnick@mail.huji.ac.il"
    role: # Contributorship roles (e.g., CRediT, https://credit.niso.org/)
      - "Conceptualization"
      - "Writing - Original Draft Preparation"
      - "Writing - Review & Editing"

  - name          : "Hila Sorka"
    affiliation   : "1"
    role:
      - "Conceptualization"
      - "Writing - Original Draft Preparation"
      - "Writing - Review & Editing"

  - name          : "Snir Barzilay"
    affiliation   : "1"
    role:
      - "Conceptualization"
      - "Writing - Original Draft Preparation"
      - "Writing - Review & Editing"

  - name          : "Jonathan D. Huppert"
    affiliation   : "1"
    role:
      - "Conceptualization"
      - "Writing - Review & Editing"
      - "Supervision"

affiliation:
  - id            : "1"
    institution   : "The Hebrew University of Jerusalem"

authornote: |
  This work was supported by ISF 1905/20 awarded to Jonathan Huppert, Sam and Helen Beber Chair of Clinical Psychology, and by SPR small research grant 2023 awarded to Elad Zlotnick.

abstract: |
  Written Exposure Therapy (WET) is a structured, evidence-based intervention initially developed for PTSD.
  This study introduces Transdiagnostic WET, a future-oriented adaptation designed to address anxiety by focusing exposure on core threats and encouraging immersive emotional engagement.
  The primary goals were to validate the efficacy of Transdiagnostic WET in reducing anxiety symptoms and to investigate mechanisms driving such changes.

  To achieve this, we conducted a randomized controlled trial (RCT) comparing WET to a neutral imagery writing task and a waitlist control group, with all interventions fully self-administered.
  Outcomes were analyzed using Bayesian multilevel linear IRT models.
  The results demonstrated that WET was highly effective, with an effect size of *d* = 0.85 compared to waitlist at two-months follow-up, and that changes in distress tolerance (*r* = 0.37) and anxiety regarding core threats (*r* = 0.39) correlated with symptom reduction.

  These findings suggest that future-oriented WET is a scalable and effective intervention for treating transdiagnostic anxiety.
  Additionally, the results highlight key mechanisms of change that warrant further exploration, including distress tolerance and threat-specific anxiety.
  The scalability and flexibility of this intervention make it a promising candidate for integration into internet-based cognitive-behavioral therapy (iCBT) programs and a powerful tool for investigating therapeutic mechanisms under varied conditions.

keywords          :
  - Core threats
  - Transdiagnostic anxiety
  - Written Exposure Therapy

#wordcount         : "X"

bibliography: "`r normalizePath('~/projects/zettlr/zotero.json')`"

floatsintext      : yes
linenumbers       : yes
draft             : no
mask              : no

figurelist        : no
tablelist         : no
footnotelist      : no

classoption       : "man"

# For apa7
header-includes:
  - |
    \makeatletter
    \renewcommand{\paragraph}{\@startsection{paragraph}{4}{\parindent}%
      {0\baselineskip \@plus 0.2ex \@minus 0.2ex}%
      {-1em}%
      {\normalfont\normalsize\bfseries\typesectitle}}
    
    \renewcommand{\subparagraph}[1]{\@startsection{subparagraph}{5}{1em}%
      {0\baselineskip \@plus 0.2ex \@minus 0.2ex}%
      {-\z@\relax}%
      {\normalfont\normalsize\bfseries\itshape\hspace{\parindent}{#1}\textit{\addperi}}{\relax}}
    \makeatother

csl               : "`r system.file('rmd', 'apa7.csl', package = 'papaja')`"
documentclass     : "apa7"

output            : papaja::apa6_pdf
#output            : papaja::apa6_docx

# output files should go to "out"
knit: (function(inputFile, encoding) {
      rmarkdown::render(inputFile, encoding=encoding, output_dir=file.path(dirname(inputFile), 'output'))}) 
---

```{r setup, include = FALSE}
library("papaja")
library('here')
```

```{r, child=c(here('docs', c('intro.Rmd')))}
```

```{r, child=c(here('docs', c('methods.Rmd')))}
```

```{r, child=c(here('docs', c('results.Rmd')))}
```

```{r, child=c(here('docs', c('discussion.Rmd')))}
```

\newpage

# References

::: {#refs custom-style="Bibliography"}
:::
